### ISSUE TITLE
tempmail api having issues? any alternative ways?

### ISSUE THREAD

**Issue by ashtrobe** [Rambeboy/blockmesh-autoreferral-bot#1]
![image](https://github.com/user-attachments/assets/f5640ba1-07b8-4763-b2d7-7ae055862365)

**Comment by Rambeboy** [comment]
Just wait and the referral will come in, that's the process of looking for a valid email

**Comment by Rambeboy** [comment]
![Screenshot_20241118_171942_Mises](https://github.com/user-attachments/assets/a7dd1311-d629-4fbe-974a-7731a53bbe5d)

**Comment by ashtrobe** [comment]
![image](https://github.com/user-attachments/assets/9f1cddad-895d-4bf7-ba10-8c1dfcd0af0a)

**Comment by Rambeboy** [comment]
You can make the command 1000 reff so that the process of searching for emails runs.

**Comment by Rambeboy** [comment]
![Screenshot_20241118_182408_Termux](https://github.com/user-attachments/assets/8d893d78-3667-4310-b5f0-c3711c4f27a2)

**Comment by ashtrobe** [comment]
could you kindly define "make the command 1000 reff"
